#'Return a list of the indices of blocks of sequential \code{NAs} in \code{base}.
#'
#'Calling \code{\link{sus}} returns a vector \code{base} with some values
#'\code{NA} and some not. \code{base_gaps()} returns a list of the indices of
#'these blocks of \code{NAs}. This function is used by \code{\link{multi_shift}}.
#'
#'@param base baseline(s) generated by \code{\link{sus}}.
#'@return A list of the indices of blocks of sequential \code{NAs} in
#'  \code{base}. If \code{base} has no \code{NAs}, return \code{NULL}. If a
#'  block of \code{NAs} exists before the first sustained shift it is ignored.
#'@examples
#'runchart:::base_gaps(c(rep(NA,5), rep(3,8), rep(NA,25)))
#'@seealso \code{\link{ticker}} \code{\link{multi_shift}}
#'@keywords internal
#'@noRd

base_gaps <- function(base) {
  stopifnot(
    is.numeric(base),
    length(base) > 0
  )

  if (!any(is.na(base)) | all(is.na(base)))
    return(NULL)

  # wbase - working base
  index <- min(which(!is.na(base)))
  shift <- NULL

  while (TRUE) {

    wbase <- base[index:length(base)]

    if (all(!is.na(wbase)))
      return(shift)

    start <- min(which(is.na(wbase))) + index - 1
    wbase <- base[start:length(base)]

    if (all(is.na(wbase)))
      return(c(shift, list(start:length(base))))

    end <- min(which(!is.na(wbase))) + start - 2
    shift <- append(shift, list(start:end))

    index <- end + 1

  }
}
