#'Create shift(s) for \code{val} using baselines generated by
#'\code{\link{sus}}.
#'
#'Shifts occur when 6 or more consecutive useful observations (non-NA and
#'different from the current baseline) land all above/below the baseline.
#'
#'@param val \code{multi_shift()} iterates along the elements of \code{val} to
#'  create shifts.
#'@param base baseline generated by \code{\link{sus}}.
#'@param base_ext extended baseline generated by \code{\link{sus}}.
#'@param trigger Number of data points required to create a shift.
#'@return A vector with all shifts observed in \code{val}. If no shifts observed,
#'  a vector full of \code{NA}s.
#'@examples
#'runchart:::multi_shift(val = c(rep(0,8), rep(1,8)),
#'base = c(rep(0,8), rep(NA,8)), base_ext = rep(0, 16))
#'@seealso \code{\link{basic_shift}}
#'@keywords internal

multi_shift <- function(val, base, base_ext, trigger = 6) {
  stopifnot(
    is.numeric(trigger),
    length(val) > 0,
    length(base) > 0,
    length(base_ext) > 0,
    length(trigger) == 1
  )

  shift <- base * NA_real_

  if (all(is.na(base)))
    return(shift)

  gaps  <- base_gaps(base)

  if (length(gaps) == 0)
    return(shift)

  for (gap in gaps) {

    if (length(gap) < trigger)
      next

    indices <- basic_shift(base_ext[gap[1]], val[gap]) + gap[1] - 1

    if (is.null(indices))
      next
    else
      shift[indices] <- val[indices]
  }

  return(shift)
}
