#'Return a list of the indices of blocks of sequential \code{NAs} in \code{base}.
#'
#'Calling \code{\link{sus()}} returns a vector \code{base} with some values
#'\code{NA} and some not. \code{base_gaps()} returns a list of the indices of
#'these blocks of \code{NAs}. This function is used by \code{\link{shift()}}.
#'
#'@param base baseline(s) generated by \code{\link{sus()}}.
#'@return A list of the indices of blocks of sequential \code{NAs} in
#'  \code{base}. If \code{base} has no \code{NAs}, return \code{NULL}. If a
#'  block of \code{NAs} exists before the first sustained shift it is ignored.
#'@examples
#'base_gaps(c(rep(NA,5), rep(3,8), rep(NA,25)))
#'@seealso \code{\link{shift_ticker()}} \code{\link{shift()}}

base_gaps <- function(base) {
  stopifnot(
    is.numeric(base),
    length(base) > 0
  )

  if (all(is.na(base)))
    1:length(base)

  if (!any(is.na(base)))
    NULL
}
